// Catálogo Durax 2026 (PDF, 144 págs.): itens e páginas do índice alfabético.
// img = foto do produto; sg = código SIAGA da foto, quando a foto vem do acervo do portfólio.
window.DURAX_CATALOGO = [
  {"name":"Fixação, Ancoragem e Movimentação","page":3,"items":[
    {"name":"Abraçadeira Nylon Branca","pages":[4],"img":"assets/produtos/dx5001br-abracadeira-de-nylon-branca.jpg"},
    {"name":"Abraçadeira Nylon Preta","pages":[4],"img":"assets/produtos/dx5001pt-abracadeira-de-nylon-preto.jpg"},
    {"name":"Abraçadeira sem Fim","pages":[5],"img":"assets/produtos/xfr0060002-abracadeira-r-sfim.jpg"},
    {"name":"Abraçadeira com Borboleta","pages":[5],"img":"assets/produtos/xfr0070001-abracadeira-c-borboleta.jpg"},
    {"name":"Abraçadeira Tipo “u”","pages":[5],"img":"assets/produtos/abracadeira-tipo-u.jpg","sg":"C10NB00884"}
  ]},
  {"name":"Ferramentas Manuais","page":6,"items":[
    {"name":"Alicate Amperimetro Digital","pages":[7],"img":"assets/produtos/xel0020002-alicate-amperimetro.jpg"},
    {"name":"Alicate Bomba D’água","pages":[7],"img":"assets/produtos/xfe0110006-alicate-bomba-d-agua.jpg"},
    {"name":"Alicate de Pressão","pages":[7],"img":"assets/produtos/alicate-pressao.jpg"},
    {"name":"Alicate Rebitador 4 Bicos","pages":[7],"img":"assets/produtos/xfe0110005-alicate-rebitador.jpg"},
    {"name":"Alicate de Bico Meia-cana","pages":[8],"img":"assets/produtos/xfe0110001-alicate-de-bico-meia-cana.jpg"},
    {"name":"Alicate Corte Diagonal","pages":[8],"img":"assets/produtos/xfe0110002-alicate-diagonal.jpg"},
    {"name":"Alicate Universal","pages":[8],"img":"assets/produtos/xfe0110003-alicate-universal.jpg"},
    {"name":"Chave Fenda com Imã","pages":[9],"img":"assets/produtos/xfe0030001-chave-fenda-com-ima.jpg"},
    {"name":"Chave Philips com Imã","pages":[9],"img":"assets/produtos/xfe0120001-chave-phillips-c-ima.jpg"},
    {"name":"Chave Canhão","pages":[10],"img":"assets/produtos/xfe0130001-chave-canhao.jpg"},
    {"name":"Chave Biela","pages":[10],"img":"assets/produtos/xfe0140001-chave-biela.jpg"},
    {"name":"Chave Combinada","pages":[11],"img":"assets/produtos/xfe0150001-chave-combinada.jpg"},
    {"name":"Chave Estrela","pages":[11],"img":"assets/produtos/xfe0160001-chave-estrela.jpg"},
    {"name":"Chave Fixa","pages":[12],"img":"assets/produtos/xfe0160001-chave-fixa.jpg"},
    {"name":"Chave Grifo","pages":[12],"img":"assets/produtos/xfe0170001-chave-grifo-amarela.jpg"},
    {"name":"Chave Inglesa Ajustável","pages":[13],"img":"assets/produtos/chave-inglesa.jpg"},
    {"name":"Colher de Pedreiro Reta","pages":[13],"img":"assets/produtos/sgmt1211001-colher-pedreiro-reta.jpg"},
    {"name":"Espátula de Aço Cabo de Plástico","pages":[13],"img":"assets/produtos/sgjk1211001-espatula-cabo-de-plastico.jpg"},
    {"name":"Colher de Pedreiro Redonda","pages":[12],"img":"assets/produtos/sgmt1211006-colher-pedreiro-redonda.jpg"},
    {"name":"Cortador de Vidro","pages":[13],"img":"assets/produtos/xfe0280001-cortador-de-vidro.jpg"},
    {"name":"Espatula de Aço Cabo Embor.","pages":[14],"img":"assets/produtos/sgjk1211008-espatula-cabo-emborrachado.jpg"},
    {"name":"Estilete","pages":[14],"img":"assets/produtos/estilete.jpg"},
    {"name":"Lâminas para Estilete - Refil","pages":[15],"img":"assets/produtos/refil-lamina-estilete.jpg"},
    {"name":"Espátula Reta Cabo de Madeira","pages":[14],"img":"assets/produtos/espatula-cabo-de-madeira.jpg"},
    {"name":"Estilete Emborrachado","pages":[14],"img":"assets/produtos/estile-emborrachado.jpg"},
    {"name":"Arco de Serra Fixo","pages":[15],"img":"assets/produtos/arco-de-serra-fixo.jpg"},
    {"name":"Arco de Serra Regulável","pages":[15],"img":"assets/produtos/arco-de-serra-regulavel.jpg"},
    {"name":"Serra Flexível Aço Carbono","pages":[15],"img":"assets/produtos/serra-flexivel-bi-metal.jpg"},
    {"name":"Lâmina de Serra Manual Bimetálica","pages":[16],"img":"assets/produtos/serra-flexivel-bi-metal.jpg"},
    {"name":"Marreta de Cabo de Fibra","pages":[17],"img":"assets/produtos/marreta-de-cabo-de-fibra.webp"},
    {"name":"Martelo de Unha","pages":[17],"img":"assets/produtos/martelo-de-unha.jpg","sg":"D03NB00053"},
    {"name":"Cabeça de Martelo de Pedreiro","pages":[18],"img":"assets/produtos/cabeca-de-martelo.jpg"},
    {"name":"Marreta Cabo de Madeira","pages":[17],"img":"assets/produtos/marreta-cabo-de-madeira.jpg"},
    {"name":"Machadinha Cabo de Fibra","pages":[18],"img":"assets/produtos/machadinha.jpg"},
    {"name":"Machado Cabo de Fibra AC","pages":[18],"img":"assets/produtos/machado-cabo-de-fibra-aco-carbono.jpg"},
    {"name":"Machado Lenhador Cabo Mad. de Carv.","pages":[19],"img":"assets/produtos/machado-lenhador-cabo-madeira-de-carvalho.jpg"},
    {"name":"Machado Lenhador Cabo Mad.","pages":[19],"img":"assets/produtos/machado-lenhador-cabo-madeira-mista.jpg"},
    {"name":"Machado Cabo de Fibra Aço Carbono","pages":[19],"img":"assets/produtos/machado-cabo-de-fibra-aco-carbono.jpg"},
    {"name":"Formão","pages":[20],"img":"assets/produtos/xfe0270003-formao.jpg"},
    {"name":"Escova Aço Manual","pages":[20],"img":"assets/produtos/escova-de-aco.jpg"},
    {"name":"Grampo Tipo C","pages":[21],"img":"assets/produtos/grampo-c.jpg"},
    {"name":"Tesoura Aviação Reta","pages":[21],"img":"assets/produtos/tesoura-aviacao-reta.jpg"},
    {"name":"Tesoura Corta Vergalhão CRV Pro","pages":[21],"img":"assets/produtos/tesoura-corta-vergalhao.jpg"},
    {"name":"Tesoura Funileiro","pages":[21],"img":"assets/produtos/tesoura-funileiro.jpg"},
    {"name":"Jogo de Chaves Torx","pages":[22],"img":"assets/produtos/d02nb00132.jpg","sg":"D02NB00132"},
    {"name":"Jogo Chave Allen","pages":[22],"img":"assets/produtos/jogo-ch-hexagonal-c-suporte-10pcs.jpg"},
    {"name":"Bits Magnéticos","pages":[22],"img":"assets/produtos/bits-torcao-ph2.jpg"},
    {"name":"Jogo Bits Magnéticos","pages":[23],"img":"assets/produtos/xfe0200001-jogo-bits-c-adap-magnetico.jpg"},
    {"name":"Trenas","pages":[23],"img":"assets/produtos/trenas.jpg"},
    {"name":"Nivel Plástico 3 Bolhas","pages":[24],"img":"assets/produtos/nivel-plastico-3-bolhas.jpg"},
    {"name":"Nível Torpedo 3 Bolhas","pages":[24],"img":"assets/produtos/nivel-torpedinho.jpg"},
    {"name":"Nivel Alumínio 3 Bolhas","pages":[24],"img":"assets/produtos/nivel-de-aluminio-viga.jpg"},
    {"name":"Nível Alumínio Tipo Cx sem Imã","pages":[25]},
    {"name":"Nível Alumínio Tipo Cx 3 Bolhas Magn.","pages":[26],"img":"assets/produtos/nivel-aluminio-tipo-caixa-3-bolhas-magnetico.jpg"},
    {"name":"Macaco Hidráulico","pages":[27],"img":"assets/produtos/macaco-hidraulico.jpg"},
    {"name":"Esquadro de Alumínio","pages":[27],"img":"assets/produtos/esquadro.jpg"},
    {"name":"Cadeado Bike com Segredo","pages":[27],"img":"assets/produtos/cadeado-bike-com-segredo.jpg","sg":"D10NB00015"}
  ]},
  {"name":"Abrasivos, Corte e Desbaste","page":28,"items":[
    {"name":"Disco de Corte Inox","pages":[29],"img":"assets/produtos/xab0050004-disco-de-corte-inox.jpg"},
    {"name":"Disco Corte Tungs. Madeira","pages":[29],"img":"assets/produtos/xab0050012-disco-corte-tungstenio-madeira.jpg"},
    {"name":"Disco Corte Vidro","pages":[29],"img":"assets/produtos/xab0050013-disco-de-corte-vidros.jpg"},
    {"name":"Disco de Desbaste","pages":[29],"img":"assets/produtos/xab0050006-disco-de-desbaste.jpg"},
    {"name":"Serra Circular Madeira","pages":[30],"img":"assets/produtos/f03nb00059-melhorada-fundo-branco.jpg","sg":"F03NB00059"},
    {"name":"Disco Diamantado","pages":[31],"img":"assets/produtos/xab0050008-disco-diamantado-liso.jpg"},
    {"name":"Disco Flap","pages":[32],"img":"assets/produtos/xab0150011-disco-flap-conico.jpg"},
    {"name":"Rebolo Diamantado","pages":[33],"img":"assets/produtos/rebolo-diamantado-turbo-para-concreto-e-pedra-rosca.jpg"},
    {"name":"Escova de Aço Copo","pages":[34],"img":"assets/produtos/escova-de-aco-copo.jpg"},
    {"name":"Escova de Circular","pages":[34],"img":"assets/produtos/escoava-de-aco-circular.jpg"},
    {"name":"Escova Tipo Pincel","pages":[35],"img":"assets/produtos/escova-tipo-pincel.webp"},
    {"name":"Lixa","pages":[35]}
  ]},
  {"name":"Perfuração e Acessórios","page":36,"items":[
    {"name":"Broca Aço Rápido Std","pages":[37],"img":"assets/produtos/sgdb1202137-broca-aco-rapido.jpg"},
    {"name":"Broca Aço Rápido Pro","pages":[37],"img":"assets/produtos/sgdb1202137-broca-aco-rapido.jpg"},
    {"name":"Broca Aço Rápido Laminada","pages":[38],"img":"assets/produtos/sgdb1202137-broca-aco-rapido.jpg"},
    {"name":"Broca Chata","pages":[39],"variants":["Standard"],"img":"assets/produtos/broca-chata.jpg"},
    {"name":"Broca Videa Concreto","pages":[39],"variants":["Extra Longa","Pro","Haste Hexagonal Pro","Padrão"],"img":"assets/produtos/xfe0120045-broca-videa-concreto.jpg"},
    {"name":"Broca 3 Pontas Aço Carbono","pages":[40],"img":"assets/produtos/broca-3-pontas.jpg"},
    {"name":"Broca Videa SDS Plus","pages":[40],"img":"assets/produtos/xfe0120024-broca-videa-sds-plus.jpg"},
    {"name":"Broca Videa Serrilhada 4 Pontas","pages":[41],"img":"assets/produtos/broca-videa-serrilhada-4-pontas.jpg"},
    {"name":"Broca Telha Fibrocimento Mourão Esp.","pages":[41],"img":"assets/produtos/sgdb1214230-broca-telha-fibrocimento-mourao.jpg"},
    {"name":"Broca Telha Fibrocimento Mourão","pages":[41],"img":"assets/produtos/sgdb1214230-broca-telha-fibrocimento-mourao.jpg"},
    {"name":"Broca Longa Madeira","pages":[42],"img":"assets/produtos/broca-longa-madeira.jpg","sg":"F01NB00223"},
    {"name":"Broca Mourão para Madeira","pages":[42],"img":"assets/produtos/broca-mourao-espiral-madeira-sem-texto-pb.jpg"},
    {"name":"Broca Espiral Madeira","pages":[42],"img":"assets/produtos/broca-mourao-espiral-madeira-sem-texto-pb.jpg"},
    {"name":"Broca para Madeira 3 Pontas","pages":[43],"img":"assets/produtos/broca-3-pontas.jpg"}
  ]},
  {"name":"Iluminação e Elétrica","page":44,"items":[
    {"name":"Alicate Amperimetro Digital","pages":[45],"img":"assets/produtos/xel0020002-alicate-amperimetro.jpg"},
    {"name":"Bocal Soquete E27 Macho","pages":[45],"img":"assets/produtos/sg-pla03pr-bocal-soquete-adaptador-e27-com-plug-macho.jpg"},
    {"name":"Base Tomada Porc. Tripolar","pages":[46],"img":"assets/produtos/xel0030003-base-tomada-porcelana-tripolar.jpg"},
    {"name":"Bocal Pendente com Rabicho","pages":[46],"img":"assets/produtos/dx8001pt-bocal-pendente-c-rabicho.jpg"},
    {"name":"Multímetro Digital","pages":[45],"img":"assets/produtos/sg-dt830b9v-multimetro-digital-basico-9v.jpg"},
    {"name":"Base Tomada Porc. Bipolar","pages":[45],"img":"assets/produtos/xel0030001-base-tomada-porcelana-bipolar.jpg"},
    {"name":"Bocal E27","pages":[46],"img":"assets/produtos/dx8002br-bocal-e27.jpg"},
    {"name":"Painel LED Emb. Plást. Ferro Driver Ext.","pages":[46]},
    {"name":"Painel LED Sob. Plást. Ferro Driver Ext.","pages":[47]},
    {"name":"Painel LED Emb. Plást. Ferro Driver Int.","pages":[48]},
    {"name":"Painel LED Sob. Plást. Ferro Driver Int.","pages":[49]},
    {"name":"Painel de LED Emb. Plást. Driver Int.","pages":[49]},
    {"name":"Painel de LED Sob. Plást. Driver Int.","pages":[50]},
    {"name":"Painel LED Emb. Alu. Ferro Driver Ext.","pages":[51],"img":"assets/produtos/dx10167-painel-led-al-emb-red.jpg"},
    {"name":"Painel LED Sob. Alu. Ferro Driver Ext.","pages":[51],"img":"assets/produtos/painel-led-al-sob-qua.jpg"},
    {"name":"Refletor LED","pages":[52],"img":"assets/produtos/dx10307-refletor-led.jpg"},
    {"name":"Painel LED Embutir Quadrado","pages":[53],"img":"assets/produtos/dx10158-painel-led-embutir.jpg"},
    {"name":"Painel LED Sobrepor Quadrado","pages":[53],"img":"assets/produtos/dx10157-painel-led-sob-qua.jpg"},
    {"name":"Painel LED Embutir Redondo","pages":[53],"img":"assets/produtos/dx10159-painel-led-emb-red.jpg"},
    {"name":"Painel LED Sobrepor Redondo","pages":[54],"img":"assets/produtos/dx10163-painel-led-sob-red.jpg"},
    {"name":"Painel LED Emb. Redondo Alumínio","pages":[54],"img":"assets/produtos/dx10167-painel-led-al-emb-red.jpg"},
    {"name":"Painel LED Emb. Quadrado de Alumínio","pages":[54]},
    {"name":"Painel LED Sob. Redondo de Alumínio","pages":[55],"img":"assets/produtos/painel-led-al-sob-red.jpg"},
    {"name":"Painel LED Sob. Redondo Alumínio","pages":[55],"img":"assets/produtos/painel-led-al-sob-red.jpg"},
    {"name":"Spot LED Embutir Quadrada","pages":[55],"img":"assets/produtos/dx10201-spot-led-emb-qua.jpg"},
    {"name":"Spot LED Embutir Redondo","pages":[56],"img":"assets/produtos/dx10202-spot-led-emb-red1.jpg"},
    {"name":"Refletor LED de Alumínio","pages":[56],"img":"assets/produtos/dx10307-refletor-led.jpg"},
    {"name":"Luminaria LED Slim","pages":[57],"img":"assets/produtos/dx10401-luminaria-led-slim.jpg"},
    {"name":"Canaleta Plástica com Fita","pages":[57],"img":"assets/produtos/sg-pct2010b-canaleta-plastica.jpg"},
    {"name":"Canaleta sem Divisória","pages":[58],"img":"assets/produtos/sg-pct1010-canaleta-s-divisoria.jpg"},
    {"name":"Adaptador Branco","pages":[58],"img":"assets/produtos/adaptador-cplug-macho.jpg"},
    {"name":"Fita Isolante","pages":[58],"img":"assets/produtos/dx7002-fita-isolante.jpg"},
    {"name":"Fita Isolante Autofusão","pages":[59],"img":"assets/produtos/fita-isolante-autofusao.jpg","sg":"A12NB00019"},
    {"name":"Pino Louça Bipolar 2P","pages":[59],"img":"assets/produtos/xel0030005-pino-louca-bipolar-2p-20a.jpg"},
    {"name":"Pino Louça Tripolar 2P","pages":[59],"img":"assets/produtos/pino-louca-tripolar.jpg"},
    {"name":"Driver para Painelo LED","pages":[59],"img":"assets/produtos/driver-para-painel-led.jpg"},
    {"name":"Conector de Derivação Perfurante","pages":[60],"img":"assets/produtos/conector-de-derivacao-perfurante.jpg","sg":"H06NB00050"},
    {"name":"Conector Elétrico em Barra Multiplo","pages":[60],"img":"assets/produtos/conector-eletrico-em-barra-multiplo.jpg"},
    {"name":"Driver para Painel LED","pages":[60],"img":"assets/produtos/driver-para-painel-led.jpg"}
  ]},
  {"name":"Hidráulica, Água e Irrigação","page":61,"items":[
    {"name":"Bomba D’água Periférica","pages":[62],"img":"assets/produtos/dx10001-bomba-periferica.jpg"},
    {"name":"Ralo Click Quadrado","pages":[62],"img":"assets/produtos/ralo-click-quadrado.jpg"},
    {"name":"Ralo Quadrado","pages":[63],"img":"assets/produtos/ralo-quadrado.jpg"},
    {"name":"Ralo Click Redondo","pages":[62],"img":"assets/produtos/ralo-click-redondo.jpg"},
    {"name":"Ralo Redondo","pages":[62],"img":"assets/produtos/ralo-redondo.jpg"},
    {"name":"Ralo de Pia","pages":[63],"img":"assets/produtos/ralo-de-pia.jpg"},
    {"name":"Chuveiro","pages":[63],"img":"assets/produtos/chuveiro.jpg"},
    {"name":"Torneira de Esfera","pages":[64],"img":"assets/produtos/torneira-esfera.jpg"},
    {"name":"Torneira de Esfera com Cadeado","pages":[64],"img":"assets/produtos/torneira-esfera-com-cadeado.jpg"},
    {"name":"Válvula Gaveta Latão","pages":[64],"img":"assets/produtos/valvula-gaveta.jpg"},
    {"name":"Torneira de Esfera Liga de Zinco","pages":[64],"img":"assets/produtos/torneira-de-esfera-liga-de-zinco.webp"},
    {"name":"Torneira para Máquina de Lavar","pages":[65],"img":"assets/produtos/torneira-de-esfera-para-maquina-de-lavar.jpg"},
    {"name":"Mangueira Jardim Anti Torsão","pages":[65],"img":"assets/produtos/i03nb00024.jpg","sg":"I03NB00024"},
    {"name":"Torneiras","pages":[65],"img":"assets/produtos/torneira.jpg"},
    {"name":"Válvula de Pia Banheiro","pages":[66],"img":"assets/produtos/i07nb00017.jpg","sg":"I07NB00017"},
    {"name":"Valvula de Pia Cozinha","pages":[66],"img":"assets/produtos/i07nb00019.jpg","sg":"I07NB00019"},
    {"name":"Válvula Esfera Liga de Zinco","pages":[66],"img":"assets/produtos/valvula-de-esfera-liga-de-zinco.jpg"},
    {"name":"Válvula de Esfera Zincada","pages":[67],"img":"assets/produtos/valvula-de-esfera-zincada.jpg"},
    {"name":"Válvula de Esfera Compacta","pages":[67],"img":"assets/produtos/valvula-de-esfera-compacta.jpg"},
    {"name":"Válvula Angular","pages":[67],"img":"assets/produtos/valvula-angular.jpg"},
    {"name":"Válvula de Retenção c/ Mola","pages":[67],"img":"assets/produtos/valvula-de-retencao-com-mola.jpg"},
    {"name":"Cano de Aço Inoxidável","pages":[68],"img":"assets/produtos/cano-de-aco-inoxidavel.jpg"},
    {"name":"Ducha Higiênica","pages":[68],"img":"assets/produtos/ducha-higienica.jpg"},
    {"name":"Engate Mangueira Aço Inox","pages":[68],"img":"assets/produtos/engate-de-mangueira-aco-inox.jpg"},
    {"name":"Mangueira Flexível Trançada","pages":[68],"img":"assets/produtos/mangueira-flexivel-trancada.jpg"},
    {"name":"Engate de Mang. Aço Inox Fêmea","pages":[69],"img":"assets/produtos/engate-de-mangueira-aco-inox.jpg"},
    {"name":"Conj. Ducha Higiênica Plástico","pages":[69],"img":"assets/produtos/conjunto-ducha-higienica-plastico.jpg"},
    {"name":"Conj. Ducha Higiênica Cromado","pages":[69]},
    {"name":"Anel Vedação p/ Vaso Sani.","pages":[70],"img":"assets/produtos/anel-vedacao-p-vaso-sanitario.jpg"},
    {"name":"Tubo de Ligação Plástico","pages":[69],"img":"assets/produtos/tubo-de-ligacao-plastico.jpg"},
    {"name":"Parafuso para Vaso Sanitário","pages":[70],"img":"assets/produtos/parafuso-p-vaso-sanitario.jpg"},
    {"name":"Desentupidor de Tubulação","pages":[70],"img":"assets/produtos/desentupidor-de-tubulacao.jpg"},
    {"name":"Vaso Sanitário","pages":[71],"img":"assets/produtos/i06nb00001.jpg","sg":"I06NB00001"},
    {"name":"Fita Veda Rosca","pages":[70],"img":"assets/produtos/fita-veda-rosca.jpg","sg":"I05NB00029"},
    {"name":"Pia Lavatório com Pedestal","pages":[71],"img":"assets/produtos/i06nb00012.jpg","sg":"I06NB00012"},
    {"name":"Bico para Torneira","pages":[71],"img":"assets/produtos/bico-para-torneira.jpg","sg":"I01NB00006"},
    {"name":"Engate Rápido para Mangueira","pages":[72],"img":"assets/produtos/engate-rapido-p-mang.jpg"},
    {"name":"Esguicho","pages":[72],"img":"assets/produtos/esguichos-pack.jpg"},
    {"name":"Emenda para Mangueira","pages":[71],"img":"assets/produtos/emenda-p-mangueira.jpg"},
    {"name":"Kit Mangueira 4PCS Engate Rápido","pages":[72],"img":"assets/produtos/kit-mangueira-4pcs-engate-rapido.webp"},
    {"name":"Pia de Aço Inox Escovado","pages":[72],"img":"assets/produtos/i07nb00061.jpg","sg":"I07NB00061"},
    {"name":"Ralo de Chão","pages":[73],"img":"assets/produtos/i07nb00026.jpg","sg":"I07NB00026"},
    {"name":"Cuba de Cerâmica Branca","pages":[73],"img":"assets/produtos/cuba-de-ceramica-branca.jpg","sg":"I06NB00021"},
    {"name":"Cuba de Vidro Transparente","pages":[73],"img":"assets/produtos/i06nb00015.jpg","sg":"I06NB00015"}
  ]},
  {"name":"Utilidades de Obra e Transporte","page":74,"items":[
    {"name":"Câmara para Carrinho de Mão","pages":[75],"img":"assets/produtos/dx1001-camara-para-carrinho-de-mao.jpg"},
    {"name":"Roda Completa com Pneu PU","pages":[75]},
    {"name":"Saco de Rafia","pages":[76],"img":"assets/produtos/saco-de-rafia.webp"},
    {"name":"Pneu para Carrinho de Mão","pages":[75],"img":"assets/produtos/sg-tr13010a-pneu-para-carrinho-de-mao.jpg"},
    {"name":"Luva de Látex","pages":[76],"img":"assets/produtos/luva-de-latex.jpg","sg":"B01NB00009"},
    {"name":"Luva de Poliéster","pages":[77]},
    {"name":"Luva Nitrilo","pages":[77],"img":"assets/produtos/luva-nitrilo.jpg","sg":"B01NB00028"},
    {"name":"Luva Revestida","pages":[77],"img":"assets/produtos/luva-revestida.jpg","sg":"B01NB00069"},
    {"name":"Luva Nitrilo Revest. Parcial Tricotada","pages":[78],"img":"assets/produtos/luva-nitrilo-revest-parcial-tricotada.jpg","sg":"B01NB00023"},
    {"name":"Luva Revest. Nitrilo Total Verde","pages":[78],"img":"assets/produtos/luva-verde.jpg"},
    {"name":"Luva de Algodão","pages":[78],"img":"assets/produtos/luva-de-algodao.jpg","sg":"B01NB00044"},
    {"name":"Luva Anticorte","pages":[78],"img":"assets/produtos/luva-anticorte.webp"},
    {"name":"Luva Nitrílica Descartável","pages":[79],"img":"assets/produtos/luva-nitrilica-descartavel.webp"},
    {"name":"Luva Descartável Incolor","pages":[79],"img":"assets/produtos/luva-descartavel-incolor.webp"},
    {"name":"Rodizio Mesa Colson Gel","pages":[79],"img":"assets/produtos/rodizio-mesa-colson-gel.jpg"}
  ]},
  {"name":"Solda, Corte Térmico e Apoio","page":81,"items":[
    {"name":"Maçarico Portátil","pages":[82],"img":"assets/produtos/macarico-culinario.jpg"},
    {"name":"Misturador de Tintas","pages":[82],"img":"assets/produtos/xfe0290001-misturador-de-tinta.jpg"},
    {"name":"Porta Eletrodo","pages":[82],"img":"assets/produtos/sgeh1102001-porta-eletrodo.jpg"},
    {"name":"Eletrodo Aco Carbono","pages":[82],"img":"assets/produtos/sgwe1101001-eletrodo-aco-carbono.jpg"}
  ]},
  {"name":"Pintura e Acabamento","page":83,"items":[
    {"name":"Aplicador de Silicone","pages":[84],"img":"assets/produtos/xfe0100001-aplicado-de-silicone.jpg"},
    {"name":"Aplicador de Silicone Heavy Duty","pages":[84],"img":"assets/produtos/xfe0100002-aplicador-de-silicone-heavy-duty.jpg"},
    {"name":"Aplicador de Silicone Tubular","pages":[84],"img":"assets/produtos/xfe0100004-aplicador-de-silicone-tubular.jpg"},
    {"name":"Lona Azul com Ilhós","pages":[85],"img":"assets/produtos/dx30001-lona-azul-c-ilhos.jpg"},
    {"name":"Lona Preta","pages":[86]},
    {"name":"Pulverizador Manual","pages":[86],"img":"assets/produtos/pulverizador-750ml.jpg"},
    {"name":"Fita para Junta de Drywall","pages":[87],"img":"assets/produtos/fita-telada-para-drywall.jpg"},
    {"name":"Fita Acrílica Dupla Face","pages":[87]},
    {"name":"Fita Antiderrapante","pages":[87],"img":"assets/produtos/fita-antiderrapante.webp"},
    {"name":"Fita Crepe","pages":[88],"img":"assets/produtos/fita-crepe.jpg","sg":"A12NB00073"},
    {"name":"Fita Crepe 247 Auto Amarela","pages":[88]},
    {"name":"Fita Crepe 248 Auto Premium Verde","pages":[88],"img":"assets/produtos/fita-crepe-248-auto-premium-verde.webp"},
    {"name":"Fita Crepe 254UV Imob Azul","pages":[89],"img":"assets/produtos/fita-crepe-254uv-imob-azul.jpg","sg":"A12NB00045"},
    {"name":"Fita de Demarcação","pages":[89],"img":"assets/produtos/fita-de-demarcacao.webp"},
    {"name":"Fita de Empacotamento","pages":[89],"img":"assets/produtos/fita-de-empacotamento.jpg","sg":"A12NB00071"},
    {"name":"Fita Espuma Dupla Face","pages":[89]},
    {"name":"Fita Papel Dupla Face","pages":[90],"img":"assets/produtos/fita-papel-dupla-face.jpg"},
    {"name":"Fita Silver","pages":[90],"img":"assets/produtos/fita-silver.jpg"},
    {"name":"Tela Extrudada Nylon","pages":[90],"img":"assets/produtos/tela-extrudada-nylon.jpg"},
    {"name":"Tela Tapume","pages":[90],"img":"assets/produtos/tela-tapume.jpg"}
  ]},
  {"name":"Suportes e Instalação","page":91,"items":[
    {"name":"Suporte Mão Francesa Preta","pages":[92],"img":"assets/produtos/mao-francesa-preta.jpg"},
    {"name":"Cantoneira para Prateleira","pages":[92],"img":"assets/produtos/cantoneira-para-prateleira.jpg","sg":"C07NB00059"},
    {"name":"Suporte Mão Francesa Branca","pages":[92],"img":"assets/produtos/mao-francesa-branca.jpg"},
    {"name":"Prateleira","pages":[93]}
  ]},
  {"name":"Jardinagem e Uso Rural","page":94,"items":[
    {"name":"Hélice Roçadeira","pages":[95],"img":"assets/produtos/lamina-rocadeira-helice.jpg"},
    {"name":"Tesoura de Poda","pages":[95],"img":"assets/produtos/tesoura-de-poda.jpg"},
    {"name":"Serrote de Poda","pages":[96],"img":"assets/produtos/serrote-de-poda.jpg"},
    {"name":"Fio de Nylon para Roçadeira Redondo","pages":[95],"img":"assets/produtos/fio-de-nylon-para-rocadeira-redondo.jpg","sg":"F03NB00251"}
  ]},
  {"name":"Ferragens","page":97,"items":[
    {"name":"Arame Galvanizado","pages":[98],"img":"assets/produtos/xfr0090013-arame-galvanizado.jpg"},
    {"name":"Arame Recozido Liso","pages":[98],"img":"assets/produtos/xfr0090002-arame-recozido-liso.jpg"},
    {"name":"Barra Roscada Zincada","pages":[99],"img":"assets/produtos/xfr0050005-barra-roscada-unc.jpg"},
    {"name":"Arame Recozido Torcido","pages":[98],"img":"assets/produtos/xfr0090001-arame-recozido-torcido.jpg"},
    {"name":"Arame Revestido PVC Verde","pages":[99],"img":"assets/produtos/arame-revestido-pvc-verde.jpg"},
    {"name":"Corrente Galvanizada Soldada","pages":[99],"img":"assets/produtos/xfr0110001-corrente.jpg"},
    {"name":"Tela Galvanizada","pages":[100],"img":"assets/produtos/xfr0050001-tela-galvanizada.jpg"},
    {"name":"Arame Farpado Galvanizado","pages":[101],"img":"assets/produtos/arame-farpado.jpg"},
    {"name":"Paraf. Drywall Trombeta Agulha","pages":[101],"img":"assets/produtos/paraf-drywall-trombeta-agulha-phs.jpg"},
    {"name":"Paraf. Chipboard","pages":[102],"img":"assets/produtos/paraf-chipboard.jpg"},
    {"name":"Paraf. Drywall Ponta Agulha","pages":[103],"img":"assets/produtos/paraf-drywall.jpg"},
    {"name":"Parafuso Telha Auto Brocante","pages":[103],"img":"assets/produtos/parafuso-telha-auto-brocante-12x8.jpg"},
    {"name":"Parafuso Telheiro","pages":[103],"img":"assets/produtos/parafuso-telheiro.jpg"},
    {"name":"Paraf. Drywall Auto Brocante","pages":[102],"img":"assets/produtos/paraf-drywall-auto-brocante.webp"},
    {"name":"Paraf.telha A.broc c/ Arruela","pages":[104],"img":"assets/produtos/paraf-telha-a-broc-c-arru.jpg"},
    {"name":"Ponteira Martelete SDS Max","pages":[104],"img":"assets/produtos/ponteira-de-martelete-max.jpg"},
    {"name":"Ponteira Martelete SDS","pages":[104],"img":"assets/produtos/ponteira-de-martelete-sds.jpg"},
    {"name":"Ponteira Canhão","pages":[105],"img":"assets/produtos/ponteira-canhao.jpg"},
    {"name":"Prego de Aço Cabeça Galvanizado","pages":[105],"img":"assets/produtos/prego-de-aco-c-cabeca-galvanizado.jpg"},
    {"name":"Prego Telheiro","pages":[105],"img":"assets/produtos/prego-telheiro.jpg"},
    {"name":"Roldana Isoladora","pages":[105],"img":"assets/produtos/roldana-isoladora.jpg"},
    {"name":"Serra Copos","pages":[106],"img":"assets/produtos/serra-copos-9pcs.jpg"},
    {"name":"Concertina Galvanizada","pages":[107],"img":"assets/produtos/concertina-galvanizada.jpg","sg":"C01NB00128"},
    {"name":"Soquete Magnético","pages":[107],"img":"assets/produtos/bit-soquete-magnetico.jpg"},
    {"name":"Talhadeira Martelete SDS Max","pages":[108],"img":"assets/produtos/talhadeira-martelete-sds-max.jpg"},
    {"name":"Talhadeira Martelete Max","pages":[108],"img":"assets/produtos/talhadeira-martelete-sds-max.jpg"},
    {"name":"Talhadeira SDS Martelete Curva","pages":[108],"img":"assets/produtos/talhadeira-sds-martelete-curva.jpg"},
    {"name":"Talhadeira Sext. SDS Plus","pages":[108],"img":"assets/produtos/talhadeira-sext-sds-plus.jpg","sg":"F07NB00002"},
    {"name":"Tensor de Aço","pages":[109],"img":"assets/produtos/tensor-de-aco.jpg","sg":"C02NB00066"},
    {"name":"Grampo de Cabo de Aço","pages":[109],"img":"assets/produtos/clips-para-cabo-de-aco.jpg"},
    {"name":"Parafuso Olhal","pages":[110],"img":"assets/produtos/olhal-parafuso.jpg"},
    {"name":"Manilha D","pages":[110],"img":"assets/produtos/manilha-d.jpg"},
    {"name":"Sapatilho para Cabo de Aço","pages":[111],"img":"assets/produtos/sapatilho-para-cabo-de-aco.jpg"},
    {"name":"Luva Alumínio Oitavada","pages":[112],"img":"assets/produtos/luva-aluminio-oitavada.jpg"},
    {"name":"Porca Sextavada","pages":[112],"img":"assets/produtos/porca-sextavada.jpg"},
    {"name":"Arruela Lisa","pages":[113],"img":"assets/produtos/arruela-zincado.jpg"},
    {"name":"Rebites Alumínio","pages":[113],"img":"assets/produtos/rebite-aluminio.jpg"},
    {"name":"Chumbador","pages":[113],"img":"assets/produtos/chumbador.jpg"},
    {"name":"Parafuso Sextavado","pages":[114],"img":"assets/produtos/parafuso-sextavado.jpg"},
    {"name":"Parafusos Máquina Fenda","pages":[115],"img":"assets/produtos/parafuso-maquinha-fenda.jpg"},
    {"name":"Parafuso Carroçeria","pages":[115],"img":"assets/produtos/parafuso-carroceria.webp"},
    {"name":"Parafuso Francês","pages":[116],"img":"assets/produtos/sg-bt11117-paraf-frances.jpg"},
    {"name":"Parafuso Aa","pages":[116],"img":"assets/produtos/paraf-aa-c-chata-phs-ziinc.jpg"},
    {"name":"Parafuso Auto Brocante","pages":[116],"img":"assets/produtos/sg-sc10117-paraf-a-brocante-c-chata-phs-zinc.jpg"},
    {"name":"Prego Cabeça Dupla","pages":[117],"img":"assets/produtos/prego-cabeca-dupla.jpg"},
    {"name":"Parafuso Cama","pages":[117],"img":"assets/produtos/sg-bt11110-paraf-cama-bicr.jpg"},
    {"name":"Paraf Sextavado Soberba","pages":[118],"img":"assets/produtos/paraf-sextavado-soberba.jpg"},
    {"name":"Prego de Aço sem Cabeça Galvanizado","pages":[118],"img":"assets/produtos/prego-de-aco-sem-cabeca-galvanized.jpg"},
    {"name":"Prego com Cabeça","pages":[119],"img":"assets/produtos/prego-com-cabeca.jpg"},
    {"name":"Prego sem Cabeça","pages":[119],"img":"assets/produtos/prego-de-aco-sem-cabeca.jpg"},
    {"name":"Prego em U","pages":[120],"img":"assets/produtos/prego-em-u.jpg"},
    {"name":"Cantoneira para Móveis","pages":[120],"img":"assets/produtos/cantoneira-para-moveis.jpg"},
    {"name":"Tela Ondulada Galvanizada","pages":[120],"img":"assets/produtos/c01nb00134.jpg","sg":"C01NB00134"},
    {"name":"Grampo C","pages":[121],"img":"assets/produtos/grampo-c.jpg"},
    {"name":"Limas","pages":[121],"img":"assets/produtos/lima-chata.jpg"},
    {"name":"Painel Soldado Galvanizado","pages":[123],"img":"assets/produtos/c01nb00129.jpg","sg":"C01NB00129"},
    {"name":"Arame Oval Galvanizado","pages":[123],"img":"assets/produtos/arame-oval-galvanizado.jpg","sg":"C01NB00140"},
    {"name":"Tensor Gancho","pages":[123],"img":"assets/produtos/tensor-gancho.webp"},
    {"name":"Grampo Perfurante","pages":[124]},
    {"name":"Corda de Polietileno Torcida 3 Pernas","pages":[124],"img":"assets/produtos/corda-de-polietileno-torcida-3-pernas.jpg"}
  ]},
  {"name":"Brindes e Diversos","page":125,"items":[
    {"name":"Bolsa Térmica","pages":[126],"img":"assets/produtos/bolsa-termica.jpg"},
    {"name":"Conj. de Facas Personalizadas","pages":[126],"img":"assets/produtos/conjunto-de-facas.jpg"},
    {"name":"Copo Térmico 350 Ml","pages":[127],"img":"assets/produtos/copos-termicos-350ml.jpg"},
    {"name":"Cadeira de Escritório Ajustável","pages":[126],"img":"assets/produtos/cadeira-de-escritorio.jpg"},
    {"name":"Conj. Faca e Garfo para Churrasco","pages":[126],"img":"assets/produtos/conjunto-faca-e-garfo-para-churrasco-inox.jpg"},
    {"name":"Guarda Sol","pages":[127],"img":"assets/produtos/guarda-sol-2m.jpg"},
    {"name":"Mochila de Lazer","pages":[127],"img":"assets/produtos/mochila-de-lazer.jpg"},
    {"name":"Pedra de Afiar Canoa","pages":[128],"img":"assets/produtos/pedra-de-afiar-canoa.jpg"},
    {"name":"Bicicleta Adulto","pages":[128],"img":"assets/produtos/xud0100002-bicicleta-adulto.jpg"},
    {"name":"Mochila de Viagem","pages":[127],"img":"assets/produtos/mochila-de-viagens.jpg"},
    {"name":"Pedra de Afiar","pages":[128],"img":"assets/produtos/xfe0300002-pedra-de-afiar.jpg"},
    {"name":"Cadeira de Praia","pages":[128],"img":"assets/produtos/cadeira-de-praia.jpg"},
    {"name":"Garrafa","pages":[129],"img":"assets/produtos/j01nb00020.jpg","sg":"J01NB00020"},
    {"name":"Caneta","pages":[129],"img":"assets/produtos/j01nb00025.jpg","sg":"J01NB00025"},
    {"name":"Caderno","pages":[129],"img":"assets/produtos/j01nb00032.jpg","sg":"J01NB00032"},
    {"name":"Mousepad","pages":[129],"img":"assets/produtos/j01nb00035.jpg","sg":"J01NB00035"},
    {"name":"Necessarie","pages":[130],"img":"assets/produtos/j01nb00036.jpg","sg":"J01NB00036"},
    {"name":"Ecobag Supermercado","pages":[130],"img":"assets/produtos/j01nb00038.jpg","sg":"J01NB00038"},
    {"name":"Chave Ferramenta","pages":[130],"img":"assets/produtos/j01nb00039.jpg","sg":"J01NB00039"},
    {"name":"Mochila/cadeira","pages":[130]}
  ]}
];
