// Gerado a partir do CATALOGO DURAX H (PDF, 126 págs.): índice + fotos.
// img = foto do produto; sg = código SIAGA da foto (acervo do portfólio).
window.DURAX_CATALOGO = [
  {"name":"Fixação, Ancoragem e Movimentação","page":8,"items":[
    {"name":"Abraçadeira Nylon Branca","pages":[10],"img":"assets/produtos/abracadeira-nylon-branca.jpg","sg":"C10NB00621"},
    {"name":"Abraçadeira Nylon Preta","pages":[10],"img":"assets/produtos/abracadeira-nylon-preta.webp"},
    {"name":"Abraçadeira sem Fim","pages":[11],"img":"assets/produtos/abracadeira-sem-fim.jpg","sg":"C10NB00088"},
    {"name":"Abraçadeira com Borboleta","pages":[11],"img":"assets/produtos/abracadeira-com-borboleta.webp"},
    {"name":"Abraçadeira Tipo “u”","pages":[11],"img":"assets/produtos/abracadeira-tipo-u.jpg","sg":"C10NB00884"}
  ]},
  {"name":"Ferramentas Manuais","page":11,"items":[
    {"name":"Alicate Amperimetro Digital","pages":[13],"img":"assets/produtos/alicate-amperimetro-digital.webp"},
    {"name":"Alicate Bomba D’água","pages":[13],"img":"assets/produtos/alicate-bomba-d-agua.webp"},
    {"name":"Alicate de Pressão","pages":[13],"img":"assets/produtos/alicate-de-pressao.jpg","sg":"D01NB00031"},
    {"name":"Alicate Rebitador 4 Bicos","pages":[12]},
    {"name":"Alicate de Bico Meia-cana","pages":[13]},
    {"name":"Alicate Corte Diagonal","pages":[14],"img":"assets/produtos/alicate-corte-diagonal.jpg","sg":"D04NB00042"},
    {"name":"Alicate Universal","pages":[14],"img":"assets/produtos/alicate-universal.jpg","sg":"D04NB00030"},
    {"name":"Chave Fenda com Imã","pages":[15],"img":"assets/produtos/chave-fenda-com-ima.webp"},
    {"name":"Chave Philips com Imã","pages":[15],"img":"assets/produtos/chave-philips-com-ima.webp"},
    {"name":"Chave Canhão","pages":[15],"img":"assets/produtos/chave-canhao.webp"},
    {"name":"Chave Biela","pages":[16],"img":"assets/produtos/chave-biela.webp"},
    {"name":"Chave Combinada","pages":[16],"img":"assets/produtos/chave-combinada.jpg","sg":"D02NB00024"},
    {"name":"Chave Estrela","pages":[17],"img":"assets/produtos/chave-estrela.jpg","sg":"D02NB00080"},
    {"name":"Chave Fixa","pages":[17],"img":"assets/produtos/chave-fixa.jpg","sg":"D02NB00273"},
    {"name":"Chave Grifo","pages":[17],"img":"assets/produtos/chave-grifo.webp"},
    {"name":"Chave Inglesa Ajustável","pages":[18],"img":"assets/produtos/chave-inglesa-ajustavel.webp"},
    {"name":"Colher de Pedreiro Reta","pages":[18],"img":"assets/produtos/colher-de-pedreiro-reta.jpg","sg":"D11NB00016"},
    {"name":"Espátula de Aço Cabo de Plástico","pages":[18],"img":"assets/produtos/espatula-de-aco-cabo-de-plastico.jpg","sg":"D11NB00004"},
    {"name":"Colher de Pedreiro Redonda","pages":[18],"img":"assets/produtos/colher-de-pedreiro-redonda.webp"},
    {"name":"Cortador de Vidro","pages":[18],"img":"assets/produtos/cortador-de-vidro.webp"},
    {"name":"Espatula de Aço Cabo Embor.","pages":[18]},
    {"name":"Estilete","pages":[19],"img":"assets/produtos/estilete.jpg","sg":"D04NB00053"},
    {"name":"Lâminas para Estilete - Refil","pages":[19],"img":"assets/produtos/laminas-para-estilete-refil.webp"},
    {"name":"Espátula Reta Cabo de Madeira","pages":[19],"img":"assets/produtos/espatula-reta-cabo-de-madeira.webp"},
    {"name":"Estilete Emborrachado","pages":[19],"img":"assets/produtos/estilete-emborrachado.jpg","sg":"D04NB00055"},
    {"name":"Arco de Serra Fixo","pages":[19],"img":"assets/produtos/arco-de-serra-fixo.jpg","sg":"D04NB00102"},
    {"name":"Arco de Serra Regulável","pages":[20],"img":"assets/produtos/arco-de-serra-regulavel.webp"},
    {"name":"Serra Flexível Aço Carbono","pages":[20],"img":"assets/produtos/serra-flexivel-aco-carbono.webp"},
    {"name":"Lâmina de Serra Manual Bimetálica","pages":[19]},
    {"name":"Marreta de Cabo de Fibra","pages":[22],"img":"assets/produtos/marreta-de-cabo-de-fibra.webp"},
    {"name":"Martelo de Unha","pages":[22],"img":"assets/produtos/martelo-de-unha.jpg","sg":"D03NB00053"},
    {"name":"Cabeça de Martelo de Pedreiro","pages":[22],"img":"assets/produtos/cabeca-de-martelo-de-pedreiro.webp"},
    {"name":"Marreta Cabo de Madeira","pages":[22],"img":"assets/produtos/marreta-cabo-de-madeira.webp"},
    {"name":"Machadinha Cabo de Fibra","pages":[23],"img":"assets/produtos/machadinha-cabo-de-fibra.jpg","sg":"D04NB00005"},
    {"name":"Machado Cabo de Fibra AC","pages":[23],"img":"assets/produtos/machado-cabo-de-fibra-ac.jpg","sg":"D04NB00010"},
    {"name":"Machado Lenhador Cabo Mad. de Carv.","pages":[22]},
    {"name":"Machado Lenhador Cabo Mad.","pages":[23],"img":"assets/produtos/machado-lenhador-cabo-mad.webp"},
    {"name":"Machado Cabo de Fibra Aço Carbono","pages":[24],"img":"assets/produtos/machado-cabo-de-fibra-aco-carbono.webp"},
    {"name":"Formão","pages":[24],"img":"assets/produtos/formao.jpg","sg":"D07NB00012"},
    {"name":"Escova Aço Manual","pages":[25],"img":"assets/produtos/escova-aco-manual.webp"},
    {"name":"Grampo Tipo C","pages":[25],"img":"assets/produtos/grampo-tipo-c.jpg","sg":"D01NB00011"},
    {"name":"Tesoura Aviação Reta","pages":[25],"img":"assets/produtos/tesoura-aviacao-reta.webp"},
    {"name":"Tesoura Corta Vergalhão CRV Pro","pages":[25],"img":"assets/produtos/tesoura-corta-vergalhao-crv-pro.jpg","sg":"D04NB00074"},
    {"name":"Tesoura Funileiro","pages":[25]},
    {"name":"Jogo de Chaves Torx","pages":[25],"img":"assets/produtos/jogo-de-chaves-torx.jpg","sg":"D02NB00130"},
    {"name":"Jogo Chave Allen","pages":[25]},
    {"name":"Bits Magnéticos","pages":[26],"img":"assets/produtos/bits-magneticos.jpg","sg":"F02NB00055"},
    {"name":"Jogo Bits Magnéticos","pages":[27],"img":"assets/produtos/jogo-bits-magneticos.webp"},
    {"name":"Trenas","pages":[27],"img":"assets/produtos/trenas.webp"},
    {"name":"Nivel Plástico 3 Bolhas","pages":[28],"img":"assets/produtos/nivel-plastico-3-bolhas.webp"},
    {"name":"Nível Torpedo 3 Bolhas","pages":[28],"img":"assets/produtos/nivel-torpedo-3-bolhas.jpg","sg":"D06NB00093"},
    {"name":"Nivel Alumínio 3 Bolhas","pages":[28],"img":"assets/produtos/nivel-aluminio-3-bolhas.jpg","sg":"D06NB00138"},
    {"name":"Nível Alumínio Tipo Cx sem Imã","pages":[28]},
    {"name":"Nível Alumínio Tipo Cx 3 Bolhas Magn.","pages":[29]},
    {"name":"Macaco Hidráulico","pages":[31],"img":"assets/produtos/macaco-hidraulico.webp"},
    {"name":"Esquadro de Alumínio","pages":[30]},
    {"name":"Cadeado Bike com Segredo","pages":[30],"img":"assets/produtos/cadeado-bike-com-segredo.jpg","sg":"D10NB00015"}
  ]},
  {"name":"Abrasivos, Corte e Desbaste","page":31,"items":[
    {"name":"Disco de Corte Inox","pages":[33],"img":"assets/produtos/disco-de-corte-inox.webp"},
    {"name":"Disco Corte Tungs. Madeira","pages":[33],"img":"assets/produtos/disco-corte-tungs-madeira.webp"},
    {"name":"Disco Corte Vidro","pages":[33],"img":"assets/produtos/disco-corte-vidro.webp"},
    {"name":"Disco de Desbaste","pages":[33],"img":"assets/produtos/disco-de-desbaste.webp"},
    {"name":"Serra Circular Madeira","pages":[34],"img":"assets/produtos/serra-circular-madeira.webp"},
    {"name":"Disco Diamantado","pages":[35],"img":"assets/produtos/disco-diamantado.jpg","sg":"F03NB00209"},
    {"name":"Disco Flap","pages":[36],"img":"assets/produtos/disco-flap.jpg","sg":"F04NB00083"},
    {"name":"Rebolo Diamantado","pages":[37],"img":"assets/produtos/rebolo-diamantado.jpg","sg":"F04NB00182"},
    {"name":"Escova de Aço Copo","pages":[38],"img":"assets/produtos/escova-de-aco-copo.webp"},
    {"name":"Escova de Circular","pages":[38],"img":"assets/produtos/escova-de-circular.webp"},
    {"name":"Escova Tipo Pincel","pages":[39],"img":"assets/produtos/escova-tipo-pincel.webp"},
    {"name":"Lixa","pages":[38]}
  ]},
  {"name":"Perfuração e Acessórios","page":40,"items":[
    {"name":"Broca Aço Rápido Std","pages":[41]},
    {"name":"Broca Aço Rápido Pro","pages":[42],"img":"assets/produtos/broca-aco-rapido-pro.webp"},
    {"name":"Broca Aço Rápido Laminada","pages":[42]},
    {"name":"Broca Chata","pages":[44],"img":"assets/produtos/broca-chata.webp","variants":["Standard"]},
    {"name":"Broca Videa Concreto","pages":[43],"variants":["Extra Longa","Pro","Haste Hexagonal Pro","Padrão"],"img":"assets/produtos/broca-videa-concreto.jpg","sg":"F01NB00310"},
    {"name":"Broca 3 Pontas Aço Carbono","pages":[44],"img":"assets/produtos/broca-3-pontas-aco-carbono.jpg","sg":"F01NB00211"},
    {"name":"Broca Videa SDS Plus","pages":[45],"img":"assets/produtos/broca-videa-sds-plus.webp"},
    {"name":"Broca Videa Serrilhada 4 Pontas","pages":[45]},
    {"name":"Broca Telha Fibrocimento Mourão Esp.","pages":[46],"img":"assets/produtos/broca-telha-fibrocimento-mourao-esp.jpg","sg":"F01NB00217"},
    {"name":"Broca Telha Fibrocimento Mourão","pages":[46],"img":"assets/produtos/broca-telha-fibrocimento-mourao.jpg","sg":"F01NB00217"},
    {"name":"Broca Longa Madeira","pages":[46],"img":"assets/produtos/broca-longa-madeira.jpg","sg":"F01NB00223"},
    {"name":"Broca Mourão para Madeira","pages":[46],"img":"assets/produtos/broca-mourao-para-madeira.jpg","sg":"F01NB00217"},
    {"name":"Broca Espiral Madeira","pages":[46],"img":"assets/produtos/broca-espiral-madeira.jpg","sg":"F01NB00232"},
    {"name":"Broca para Madeira 3 Pontas","pages":[46],"img":"assets/produtos/broca-para-madeira-3-pontas.jpg","sg":"F01NB00211"}
  ]},
  {"name":"Iluminação e Elétrica","page":47,"items":[
    {"name":"Alicate Amperimetro Digital","pages":[13],"img":"assets/produtos/alicate-amperimetro-digital.webp"},
    {"name":"Bocal Soquete E27 Macho","pages":[49],"img":"assets/produtos/bocal-soquete-e27-macho.webp"},
    {"name":"Base Tomada Porc. Tripolar","pages":[49],"img":"assets/produtos/base-tomada-porc-tripolar.jpg","sg":"H05NB00004"},
    {"name":"Bocal Pendente com Rabicho","pages":[49],"img":"assets/produtos/bocal-pendente-com-rabicho.webp"},
    {"name":"Multímetro Digital","pages":[49],"img":"assets/produtos/multimetro-digital.jpg","sg":"H07NB00002"},
    {"name":"Base Tomada Porc. Bipolar","pages":[49],"img":"assets/produtos/base-tomada-porc-bipolar.jpg","sg":"H05NB00003"},
    {"name":"Bocal E27","pages":[49],"img":"assets/produtos/bocal-e27.webp"},
    {"name":"Painel LED Emb. Plást. Ferro Driver Ext.","pages":[49]},
    {"name":"Painel LED Sob. Plást. Ferro Driver Ext.","pages":[49]},
    {"name":"Painel LED Emb. Plást. Ferro Driver Int.","pages":[50]},
    {"name":"Painel LED Sob. Plást. Ferro Driver Int.","pages":[50]},
    {"name":"Painel de LED Emb. Plást. Driver Int.","pages":[51]},
    {"name":"Painel de LED Sob. Plást. Driver Int.","pages":[51]},
    {"name":"Painel LED Emb. Alu. Ferro Driver Ext.","pages":[52]},
    {"name":"Painel LED Sob. Alu. Ferro Driver Ext.","pages":[52]},
    {"name":"Refletor LED","pages":[53],"img":"assets/produtos/refletor-led.jpg","sg":"H02NB00007"},
    {"name":"Painel LED Embutir Quadrado","pages":[54],"img":"assets/produtos/painel-led-embutir-quadrado.jpg","sg":"H01NB00095"},
    {"name":"Painel LED Sobrepor Quadrado","pages":[54],"img":"assets/produtos/painel-led-sobrepor-quadrado.jpg","sg":"H01NB00090"},
    {"name":"Painel LED Embutir Redondo","pages":[54],"img":"assets/produtos/painel-led-embutir-redondo.webp"},
    {"name":"Painel LED Sobrepor Redondo","pages":[55],"img":"assets/produtos/painel-led-sobrepor-redondo.jpg","sg":"H01NB00123"},
    {"name":"Painel LED Emb. Redondo Alumínio","pages":[54]},
    {"name":"Painel LED Emb. Quadrado de Alumínio","pages":[54]},
    {"name":"Painel LED Sob. Redondo de Alumínio","pages":[54]},
    {"name":"Painel LED Sob. Redondo Alumínio","pages":[55]},
    {"name":"Spot LED Embutir Quadrada","pages":[56],"img":"assets/produtos/spot-led-embutir-quadrada.webp"},
    {"name":"Spot LED Embutir Redondo","pages":[56],"img":"assets/produtos/spot-led-embutir-redondo.webp"},
    {"name":"Refletor LED de Alumínio","pages":[57],"img":"assets/produtos/refletor-led-de-aluminio.jpg","sg":"H02NB00007"},
    {"name":"Luminaria LED Slim","pages":[57],"img":"assets/produtos/luminaria-led-slim.jpg","sg":"H01NB00019"},
    {"name":"Canaleta Plástica com Fita","pages":[57],"img":"assets/produtos/canaleta-plastica-com-fita.jpg","sg":"C10NB00905"},
    {"name":"Canaleta sem Divisória","pages":[57],"img":"assets/produtos/canaleta-sem-divisoria.webp"},
    {"name":"Adaptador Branco","pages":[58],"img":"assets/produtos/adaptador-branco.webp"},
    {"name":"Fita Isolante","pages":[57],"img":"assets/produtos/fita-isolante.jpg","sg":"A12NB00009"},
    {"name":"Fita Isolante Autofusão","pages":[58],"img":"assets/produtos/fita-isolante-autofusao.jpg","sg":"A12NB00019"},
    {"name":"Pino Louça Bipolar 2P","pages":[59],"img":"assets/produtos/pino-louca-bipolar-2p.webp"},
    {"name":"Pino Louça Tripolar 2P","pages":[59],"img":"assets/produtos/pino-louca-tripolar-2p.webp"},
    {"name":"Driver para Painelo LED","pages":[58]},
    {"name":"Conector de Derivação Perfurante","pages":[59],"img":"assets/produtos/conector-de-derivacao-perfurante.jpg","sg":"H06NB00050"},
    {"name":"Conector Elétrico em Barra Multiplo","pages":[59],"img":"assets/produtos/conector-eletrico-em-barra-multiplo.jpg","sg":"H06NB00051"},
    {"name":"Driver para Painel LED","pages":[59]}
  ]},
  {"name":"Hidráulica, Água e Irrigação","page":60,"items":[
    {"name":"Bomba D’água Periférica","pages":[62],"img":"assets/produtos/bomba-d-agua-periferica.jpg","sg":"E11NB00007"},
    {"name":"Ralo Click Quadrado","pages":[62],"img":"assets/produtos/ralo-click-quadrado.webp"},
    {"name":"Ralo Quadrado","pages":[62],"img":"assets/produtos/ralo-quadrado.webp"},
    {"name":"Ralo Click Redondo","pages":[62],"img":"assets/produtos/ralo-click-redondo.webp"},
    {"name":"Ralo Redondo","pages":[62],"img":"assets/produtos/ralo-redondo.webp"},
    {"name":"Ralo de Pia","pages":[62],"img":"assets/produtos/ralo-de-pia.webp"},
    {"name":"Chuveiro","pages":[62]},
    {"name":"Torneira de Esfera","pages":[63],"img":"assets/produtos/torneira-de-esfera.webp"},
    {"name":"Torneira de Esfera com Cadeado","pages":[62],"img":"assets/produtos/torneira-de-esfera-com-cadeado.jpg","sg":"I02NB00018"},
    {"name":"Válvula Gaveta Latão","pages":[63],"img":"assets/produtos/valvula-gaveta-latao.webp"},
    {"name":"Torneira de Esfera Liga de Zinco","pages":[63],"img":"assets/produtos/torneira-de-esfera-liga-de-zinco.webp"},
    {"name":"Torneira para Máquina de Lavar","pages":[63],"img":"assets/produtos/torneira-para-maquina-de-lavar.webp"},
    {"name":"Mangueira Jardim Anti Torsão","pages":[63]},
    {"name":"Torneiras","pages":[64],"img":"assets/produtos/torneiras.webp"},
    {"name":"Válvula de Pia Banheiro","pages":[64]},
    {"name":"Valvula de Pia Cozinha","pages":[64]},
    {"name":"Válvula Esfera Liga de Zinco","pages":[65],"img":"assets/produtos/valvula-esfera-liga-de-zinco.webp"},
    {"name":"Válvula de Esfera Zincada","pages":[65],"img":"assets/produtos/valvula-de-esfera-zincada.jpg","sg":"I02NB00013"},
    {"name":"Válvula de Esfera Compacta","pages":[66],"img":"assets/produtos/valvula-de-esfera-compacta.webp"},
    {"name":"Válvula Angular","pages":[66],"img":"assets/produtos/valvula-angular.webp"},
    {"name":"Válvula de Retenção c/ Mola","pages":[66],"img":"assets/produtos/valvula-de-retencao-c-mola.webp"},
    {"name":"Cano de Aço Inoxidável","pages":[67],"img":"assets/produtos/cano-de-aco-inoxidavel.webp"},
    {"name":"Ducha Higiênica","pages":[67],"img":"assets/produtos/ducha-higienica.webp"},
    {"name":"Engate Mangueira Aço Inox","pages":[67],"img":"assets/produtos/engate-mangueira-aco-inox.webp"},
    {"name":"Mangueira Flexível Trançada","pages":[67],"img":"assets/produtos/mangueira-flexivel-trancada.webp"},
    {"name":"Engate de Mang. Aço Inox Fêmea","pages":[67]},
    {"name":"Conj. Ducha Higiênica Plástico","pages":[67]},
    {"name":"Conj. Ducha Higiênica Cromado","pages":[67]},
    {"name":"Anel Vedação p/ Vaso Sani.","pages":[68],"img":"assets/produtos/anel-vedacao-p-vaso-sani.webp"},
    {"name":"Tubo de Ligação Plástico","pages":[68],"img":"assets/produtos/tubo-de-ligacao-plastico.webp"},
    {"name":"Parafuso para Vaso Sanitário","pages":[69],"img":"assets/produtos/parafuso-para-vaso-sanitario.webp"},
    {"name":"Desentupidor de Tubulação","pages":[69],"img":"assets/produtos/desentupidor-de-tubulacao.webp"},
    {"name":"Vaso Sanitário","pages":[68]},
    {"name":"Fita Veda Rosca","pages":[69],"img":"assets/produtos/fita-veda-rosca.jpg","sg":"I05NB00029"},
    {"name":"Pia Lavatório com Pedestal","pages":[69],"img":"assets/produtos/pia-lavatorio-com-pedestal.jpg","sg":"I06NB00014"},
    {"name":"Bico para Torneira","pages":[70],"img":"assets/produtos/bico-para-torneira.jpg","sg":"I01NB00006"},
    {"name":"Engate Rápido para Mangueira","pages":[69]},
    {"name":"Esguicho","pages":[70],"img":"assets/produtos/esguicho.webp"},
    {"name":"Emenda para Mangueira","pages":[70],"img":"assets/produtos/emenda-para-mangueira.webp"},
    {"name":"Kit Mangueira 4PCS Engate Rápido","pages":[71],"img":"assets/produtos/kit-mangueira-4pcs-engate-rapido.webp"},
    {"name":"Pia de Aço Inox Escovado","pages":[70],"img":"assets/produtos/pia-de-aco-inox-escovado.jpg","sg":"I07NB00068"},
    {"name":"Ralo de Chão","pages":[70]},
    {"name":"Cuba de Cerâmica Branca","pages":[71],"img":"assets/produtos/cuba-de-ceramica-branca.jpg","sg":"I06NB00021"},
    {"name":"Cuba de Vidro Transparente","pages":[71],"img":"assets/produtos/cuba-de-vidro-transparente.jpg","sg":"I06NB00016"}
  ]},
  {"name":"Utilidades de Obra e Transporte","page":72,"items":[
    {"name":"Câmara para Carrinho de Mão","pages":[74],"img":"assets/produtos/camara-para-carrinho-de-mao.jpg","sg":"G06NB00026"},
    {"name":"Roda Completa com Pneu PU","pages":[73]},
    {"name":"Saco de Rafia","pages":[74],"img":"assets/produtos/saco-de-rafia.webp"},
    {"name":"Pneu para Carrinho de Mão","pages":[74],"img":"assets/produtos/pneu-para-carrinho-de-mao.jpg","sg":"G06NB00012"},
    {"name":"Luva de Látex","pages":[75],"img":"assets/produtos/luva-de-latex.jpg","sg":"B01NB00009"},
    {"name":"Luva de Poliéster","pages":[74]},
    {"name":"Luva Nitrilo","pages":[75],"img":"assets/produtos/luva-nitrilo.jpg","sg":"B01NB00028"},
    {"name":"Luva Revestida","pages":[76],"img":"assets/produtos/luva-revestida.jpg","sg":"B01NB00069"},
    {"name":"Luva Nitrilo Revest. Parcial Tricotada","pages":[75],"img":"assets/produtos/luva-nitrilo-revest-parcial-tricotada.jpg","sg":"B01NB00023"},
    {"name":"Luva Revest. Nitrilo Total Verde","pages":[76],"img":"assets/produtos/luva-revest-nitrilo-total-verde.jpg","sg":"B01NB00028"},
    {"name":"Luva de Algodão","pages":[76],"img":"assets/produtos/luva-de-algodao.jpg","sg":"B01NB00044"},
    {"name":"Luva Anticorte","pages":[77],"img":"assets/produtos/luva-anticorte.webp"},
    {"name":"Luva Nitrílica Descartável","pages":[77],"img":"assets/produtos/luva-nitrilica-descartavel.webp"},
    {"name":"Luva Descartável Incolor","pages":[77],"img":"assets/produtos/luva-descartavel-incolor.webp"},
    {"name":"Rodizio Mesa Colson Gel","pages":[77],"img":"assets/produtos/rodizio-mesa-colson-gel.jpg","sg":"C09NB00017"}
  ]},
  {"name":"Solda, Corte Térmico e Apoio","page":78,"items":[
    {"name":"Maçarico Portátil","pages":[79]},
    {"name":"Misturador de Tintas","pages":[79],"img":"assets/produtos/misturador-de-tintas.jpg","sg":"F08NB00003"},
    {"name":"Porta Eletrodo","pages":[80],"img":"assets/produtos/porta-eletrodo.jpg","sg":"F05NB00022"},
    {"name":"Eletrodo Aco Carbono","pages":[80],"img":"assets/produtos/eletrodo-aco-carbono.jpg","sg":"F05NB00006"}
  ]},
  {"name":"Pintura e Acabamento","page":80,"items":[
    {"name":"Aplicador de Silicone","pages":[81]},
    {"name":"Aplicador de Silicone Heavy Duty","pages":[81]},
    {"name":"Aplicador de Silicone Tubular","pages":[82],"img":"assets/produtos/aplicador-de-silicone-tubular.webp"},
    {"name":"Lona Azul com Ilhós","pages":[82],"img":"assets/produtos/lona-azul-com-ilhos.jpg","sg":"C11NB00108"},
    {"name":"Lona Preta","pages":[83]},
    {"name":"Pulverizador Manual","pages":[84],"img":"assets/produtos/pulverizador-manual.jpg","sg":"I01NB00022"},
    {"name":"Fita para Junta de Drywall","pages":[85],"img":"assets/produtos/fita-para-junta-de-drywall.jpg","sg":"A12NB00021"},
    {"name":"Fita Acrílica Dupla Face","pages":[84]},
    {"name":"Fita Antiderrapante","pages":[85],"img":"assets/produtos/fita-antiderrapante.webp"},
    {"name":"Fita Crepe","pages":[86],"img":"assets/produtos/fita-crepe.jpg","sg":"A12NB00073"},
    {"name":"Fita Crepe 247 Auto Amarela","pages":[85]},
    {"name":"Fita Crepe 248 Auto Premium Verde","pages":[86],"img":"assets/produtos/fita-crepe-248-auto-premium-verde.webp"},
    {"name":"Fita Crepe 254UV Imob Azul","pages":[86],"img":"assets/produtos/fita-crepe-254uv-imob-azul.jpg","sg":"A12NB00045"},
    {"name":"Fita de Demarcação","pages":[87],"img":"assets/produtos/fita-de-demarcacao.webp"},
    {"name":"Fita de Empacotamento","pages":[86],"img":"assets/produtos/fita-de-empacotamento.jpg","sg":"A12NB00071"},
    {"name":"Fita Espuma Dupla Face","pages":[86]},
    {"name":"Fita Papel Dupla Face","pages":[87]},
    {"name":"Fita Silver","pages":[87]},
    {"name":"Tela Extrudada Nylon","pages":[87]},
    {"name":"Tela Tapume","pages":[88],"img":"assets/produtos/tela-tapume.jpg","sg":"C11NB00185"}
  ]},
  {"name":"Suportes e Instalação","page":99,"items":[
    {"name":"Suporte Mão Francesa Preta","pages":[91],"img":"assets/produtos/suporte-mao-francesa-preta.webp"},
    {"name":"Cantoneira para Prateleira","pages":[100],"img":"assets/produtos/cantoneira-para-prateleira.jpg","sg":"C07NB00059"},
    {"name":"Suporte Mão Francesa Branca","pages":[91],"img":"assets/produtos/suporte-mao-francesa-branca.webp"},
    {"name":"Prateleira","pages":[100]}
  ]},
  {"name":"Jardinagem e Uso Rural","page":101,"items":[
    {"name":"Hélice Roçadeira","pages":[93],"img":"assets/produtos/helice-rocadeira.webp"},
    {"name":"Tesoura de Poda","pages":[93],"img":"assets/produtos/tesoura-de-poda.jpg","sg":"D04NB00148"},
    {"name":"Serrote de Poda","pages":[102],"img":"assets/produtos/serrote-de-poda.jpg","sg":"D04NB00133"},
    {"name":"Fio de Nylon para Roçadeira Redondo","pages":[102],"img":"assets/produtos/fio-de-nylon-para-rocadeira-redondo.jpg","sg":"F03NB00251"}
  ]},
  {"name":"Ferragens","page":103,"items":[
    {"name":"Arame Galvanizado","pages":[95],"img":"assets/produtos/arame-galvanizado.jpg","sg":"C01NB00092"},
    {"name":"Arame Recozido Liso","pages":[95],"img":"assets/produtos/arame-recozido-liso.jpg","sg":"C01NB00005"},
    {"name":"Barra Roscada Zincada","pages":[95],"img":"assets/produtos/barra-roscada-zincada.jpg","sg":"C06NB00284"},
    {"name":"Arame Recozido Torcido","pages":[95],"img":"assets/produtos/arame-recozido-torcido.jpg","sg":"C01NB00001"},
    {"name":"Arame Revestido PVC Verde","pages":[96],"img":"assets/produtos/arame-revestido-pvc-verde.jpg","sg":"C01NB00010"},
    {"name":"Corrente Galvanizada Soldada","pages":[96],"img":"assets/produtos/corrente-galvanizada-soldada.jpg","sg":"C02NB00039"},
    {"name":"Tela Galvanizada","pages":[97],"img":"assets/produtos/tela-galvanizada.jpg","sg":"C01NB00064"},
    {"name":"Arame Farpado Galvanizado","pages":[98],"img":"assets/produtos/arame-farpado-galvanizado.jpg","sg":"C01NB00125"},
    {"name":"Paraf. Drywall Trombeta Agulha","pages":[98],"img":"assets/produtos/paraf-drywall-trombeta-agulha.jpg","sg":"C03NB00125"},
    {"name":"Paraf. Chipboard","pages":[98],"img":"assets/produtos/paraf-chipboard.jpg","sg":"C03NB00052"},
    {"name":"Paraf. Drywall Ponta Agulha","pages":[99],"img":"assets/produtos/paraf-drywall-ponta-agulha.jpg","sg":"C03NB00125"},
    {"name":"Parafuso Telha Auto Brocante","pages":[99],"img":"assets/produtos/parafuso-telha-auto-brocante.jpg","sg":"C04NB00033"},
    {"name":"Parafuso Telheiro","pages":[99],"img":"assets/produtos/parafuso-telheiro.jpg","sg":"C03NB00138"},
    {"name":"Paraf. Drywall Auto Brocante","pages":[99],"img":"assets/produtos/paraf-drywall-auto-brocante.webp"},
    {"name":"Paraf.telha A.broc c/ Arruela","pages":[100],"img":"assets/produtos/paraf-telha-a-broc-c-arruela.jpg","sg":"C04NB00040"},
    {"name":"Ponteira Martelete SDS Max","pages":[100],"img":"assets/produtos/ponteira-martelete-sds-max.webp"},
    {"name":"Ponteira Martelete SDS","pages":[100],"img":"assets/produtos/ponteira-martelete-sds.webp"},
    {"name":"Ponteira Canhão","pages":[110]},
    {"name":"Prego de Aço Cabeça Galvanizado","pages":[101],"img":"assets/produtos/prego-de-aco-cabeca-galvanizado.webp"},
    {"name":"Prego Telheiro","pages":[101],"img":"assets/produtos/prego-telheiro.jpg","sg":"C06NB00250"},
    {"name":"Roldana Isoladora","pages":[101],"img":"assets/produtos/roldana-isoladora.jpg","sg":"H06NB00025"},
    {"name":"Serra Copos","pages":[102],"img":"assets/produtos/serra-copos.webp"},
    {"name":"Concertina Galvanizada","pages":[112],"img":"assets/produtos/concertina-galvanizada.jpg","sg":"C01NB00128"},
    {"name":"Soquete Magnético","pages":[103],"img":"assets/produtos/soquete-magnetico.webp"},
    {"name":"Talhadeira Martelete SDS Max","pages":[104],"img":"assets/produtos/talhadeira-martelete-sds-max.webp"},
    {"name":"Talhadeira Martelete Max","pages":[104],"img":"assets/produtos/talhadeira-martelete-max.webp"},
    {"name":"Talhadeira SDS Martelete Curva","pages":[104],"img":"assets/produtos/talhadeira-sds-martelete-curva.webp"},
    {"name":"Talhadeira Sext. SDS Plus","pages":[113],"img":"assets/produtos/talhadeira-sext-sds-plus.jpg","sg":"F07NB00002"},
    {"name":"Tensor de Aço","pages":[105],"img":"assets/produtos/tensor-de-aco.jpg","sg":"C02NB00066"},
    {"name":"Grampo de Cabo de Aço","pages":[105],"img":"assets/produtos/grampo-de-cabo-de-aco.webp"},
    {"name":"Parafuso Olhal","pages":[106],"img":"assets/produtos/parafuso-olhal.jpg","sg":"C02NB00135"},
    {"name":"Manilha D","pages":[106],"img":"assets/produtos/manilha-d.jpg","sg":"C02NB00117"},
    {"name":"Sapatilho para Cabo de Aço","pages":[106],"img":"assets/produtos/sapatilho-para-cabo-de-aco.jpg","sg":"C02NB00157"},
    {"name":"Luva Alumínio Oitavada","pages":[107],"img":"assets/produtos/luva-aluminio-oitavada.jpg","sg":"C02NB00178"},
    {"name":"Porca Sextavada","pages":[108],"img":"assets/produtos/porca-sextavada.jpg","sg":"C06NB00089"},
    {"name":"Arruela Lisa","pages":[108],"img":"assets/produtos/arruela-lisa.jpg","sg":"C06NB00118"},
    {"name":"Rebites Alumínio","pages":[108],"img":"assets/produtos/rebites-aluminio.jpg","sg":"C06NB00148"},
    {"name":"Chumbador","pages":[109],"img":"assets/produtos/chumbador.jpg","sg":"C06NB00302"},
    {"name":"Parafuso Sextavado","pages":[110],"img":"assets/produtos/parafuso-sextavado.webp"},
    {"name":"Parafusos Máquina Fenda","pages":[110],"img":"assets/produtos/parafusos-maquina-fenda.webp"},
    {"name":"Parafuso Carroçeria","pages":[111],"img":"assets/produtos/parafuso-carroceria.webp"},
    {"name":"Parafuso Francês","pages":[111],"img":"assets/produtos/parafuso-frances.jpg","sg":"C06NB00069"},
    {"name":"Parafuso Aa","pages":[111],"img":"assets/produtos/parafuso-aa.jpg","sg":"C03NB00115"},
    {"name":"Parafuso Auto Brocante","pages":[112],"img":"assets/produtos/parafuso-auto-brocante.jpg","sg":"C04NB00033"},
    {"name":"Prego Cabeça Dupla","pages":[112],"img":"assets/produtos/prego-cabeca-dupla.jpg","sg":"C06NB00185"},
    {"name":"Parafuso Cama","pages":[112],"img":"assets/produtos/parafuso-cama.webp"},
    {"name":"Paraf Sextavado Soberba","pages":[113],"img":"assets/produtos/paraf-sextavado-soberba.webp"},
    {"name":"Prego de Aço sem Cabeça Galvanizado","pages":[113],"img":"assets/produtos/prego-de-aco-sem-cabeca-galvanizado.jpg","sg":"C06NB00215"},
    {"name":"Prego com Cabeça","pages":[114],"img":"assets/produtos/prego-com-cabeca.webp"},
    {"name":"Prego sem Cabeça","pages":[123],"img":"assets/produtos/prego-sem-cabeca.jpg","sg":"C06NB00215"},
    {"name":"Prego em U","pages":[124]},
    {"name":"Cantoneira para Móveis","pages":[115],"img":"assets/produtos/cantoneira-para-moveis.jpg","sg":"C07NB00009"},
    {"name":"Tela Ondulada Galvanizada","pages":[124]},
    {"name":"Grampo C","pages":[116],"img":"assets/produtos/grampo-c.webp"},
    {"name":"Limas","pages":[116],"img":"assets/produtos/limas.jpg","sg":"D07NB00055"},
    {"name":"Painel Soldado Galvanizado","pages":[127],"img":"assets/produtos/painel-soldado-galvanizado.jpg","sg":"C01NB00132"},
    {"name":"Arame Oval Galvanizado","pages":[128],"img":"assets/produtos/arame-oval-galvanizado.jpg","sg":"C01NB00140"},
    {"name":"Tensor Gancho","pages":[119],"img":"assets/produtos/tensor-gancho.webp"},
    {"name":"Grampo Perfurante","pages":[128]},
    {"name":"Corda de Polietileno Torcida 3 Pernas","pages":[129],"img":"assets/produtos/corda-de-polietileno-torcida-3-pernas.jpg","sg":"C02NB00230"}
  ]},
  {"name":"Brindes e Diversos","page":30,"items":[
    {"name":"Bolsa Térmica","pages":[131],"img":"assets/produtos/bolsa-termica.jpg","sg":"J01NB00011"},
    {"name":"Conj. de Facas Personalizadas","pages":[131]},
    {"name":"Copo Térmico 350 Ml","pages":[131]},
    {"name":"Cadeira de Escritório Ajustável","pages":[122],"img":"assets/produtos/cadeira-de-escritorio-ajustavel.jpg","sg":"J01NB00002"},
    {"name":"Conj. Faca e Garfo para Churrasco","pages":[122],"img":"assets/produtos/conj-faca-e-garfo-para-churrasco.jpg","sg":"J01NB00013"},
    {"name":"Guarda Sol","pages":[122],"img":"assets/produtos/guarda-sol.webp"},
    {"name":"Mochila de Lazer","pages":[132]},
    {"name":"Pedra de Afiar Canoa","pages":[132],"img":"assets/produtos/pedra-de-afiar-canoa.jpg","sg":"D07NB00063"},
    {"name":"Bicicleta Adulto","pages":[123],"img":"assets/produtos/bicicleta-adulto.webp"},
    {"name":"Mochila de Viagem","pages":[123],"img":"assets/produtos/mochila-de-viagem.webp"},
    {"name":"Pedra de Afiar","pages":[123],"img":"assets/produtos/pedra-de-afiar.jpg","sg":"D07NB00062"},
    {"name":"Cadeira de Praia","pages":[123],"img":"assets/produtos/cadeira-de-praia.webp"},
    {"name":"Garrafa","pages":[133],"img":"assets/produtos/garrafa.jpg","sg":"J01NB00023"},
    {"name":"Caneta","pages":[133]},
    {"name":"Caderno","pages":[133]},
    {"name":"Mousepad","pages":[134]},
    {"name":"Necessarie","pages":[134],"img":"assets/produtos/necessarie.jpg","sg":"J01NB00036"},
    {"name":"Ecobag Supermercado","pages":[134]},
    {"name":"Chave Ferramenta","pages":[134]},
    {"name":"Mochila/cadeira","pages":[135]}
  ]}
];
